### ISSUE TITLE
`regl` won't build with `gl: 4.0.1`

### ISSUE THREAD

**Issue by thomcom** [regl-project/regl#655]
`gl` needs to be updated to `5.0.3` in order to build this project.

**Comment by kevzettler** [comment]
I'm seeing a failure from `npm install`  looks like it stems from `gl@4.0.1`

```
prebuild ERR! stack Error: Command failed: /usr/local/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
prebuild ERR! stack   File "<string>", line 1
prebuild ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
prebuild ERR! stack                       ^
prebuild ERR! stack SyntaxError: invalid syntax
prebuild ERR! stack
prebuild ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
prebuild ERR! stack     at ChildProcess.emit (events.js:314:20)
prebuild ERR! stack     at maybeClose (internal/child_process.js:1022:16)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
prebuild ERR! not ok
prebuild ERR! build Error: Command failed: /usr/local/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
prebuild ERR! build   File "<string>", line 1
prebuild ERR! build     import sys; print "%s.%s.%s" % sys.version_info[:3];
prebuild ERR! build                       ^
prebuild ERR! build SyntaxError: invalid syntax
prebuild ERR! build
prebuild ERR! build     at ChildProcess.exithandler (child_process.js:308:12)
prebuild ERR! build     at ChildProcess.emit (events.js:314:20)
prebuild ERR! build     at maybeClose (internal/child_process.js:1022:16)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gl@4.0.1 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gl@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
